sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - TRAVIS_NODE_VERSION="5"

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

